In [3]:
import pandas as pd
import numpy as np

# Create a DataFrame

In pandas we Create DateFrame using Dict and list.

In [6]:
#Dict
data = {
    "Name":['John','Anna','Peter','Linda'],
    "Age":[28,34,29,42],
    "City":['New York','Paris','Berlin','London'],
    'Salary':[65000,7000,62000,85000]   
}
df=pd.DataFrame(data)

In [7]:
df

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris    7000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [10]:
#list
data_list=[
    ['John',28,'New York',65000],
    ['Anna',34,'Paris',7000],
    ['Peter',29,'Berlin',62000],
    ['Linda',42,'London',85000]
]

col=['Name','Age','City','Salary']
df2=pd.DataFrame(data_list,columns=col)

In [11]:
df2

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris    7000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

# Selection and Indexing of Columns

In [12]:
 df2

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris    7000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [18]:
df['Name'] # For targeting single Column

0     John
1     Anna
2    Peter
3    Linda
Name: Name, dtype: object

In [17]:
df[['Name','City']] # For targeting multiple Column

    Name      City
0   John  New York
1   Anna     Paris
2  Peter    Berlin
3  Linda    London

Creating a new Column

In [20]:
df2['Designation']=["Dr.","Eng.","Dr.","Eng."]

In [21]:
df2

    Name  Age      City  Salary Designation
0   John   28  New York   65000         Dr.
1   Anna   34     Paris    7000        Eng.
2  Peter   29    Berlin   62000         Dr.
3  Linda   42    London   85000        Eng.

Removing Column

In [22]:
df2.drop("Designation",axis=1) #like for snapshot(view)

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris    7000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [23]:
df2

    Name  Age      City  Salary Designation
0   John   28  New York   65000         Dr.
1   Anna   34     Paris    7000        Eng.
2  Peter   29    Berlin   62000         Dr.
3  Linda   42    London   85000        Eng.

In [24]:
df2.drop("Designation",axis=1,inplace=True) # For forever delete

In [25]:
df2

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris    7000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [26]:
df.drop(["Name","Age"],axis=1) #for multiple

       City  Salary
0  New York   65000
1     Paris    7000
2    Berlin   62000
3    London   85000

In [27]:
df2

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris    7000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [28]:
df2.drop(0,axis=0)

    Name  Age    City  Salary
1   Anna   34   Paris    7000
2  Peter   29  Berlin   62000
3  Linda   42  London   85000

Selecting Rows

In [29]:
df2

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris    7000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [33]:
df2.loc[0] #loc means location

Name          John
Age             28
City      New York
Salary       65000
Name: 0, dtype: object

In [34]:
df2.loc[[0,3]] # for selecting multiple rows

    Name  Age      City  Salary
0   John   28  New York   65000
3  Linda   42    London   85000

In [32]:
df2.iloc[2] #indexing/Lables location like :2

Name       Peter
Age           29
City      Berlin
Salary     62000
Name: 2, dtype: object

Selecting Subsets of Rows and Columns

In [36]:
df2.loc[[2,3]][["Name","Age"]]

    Name  Age
2  Peter   29
3  Linda   42

Conditional Selection

In [37]:
df2

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris    7000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [39]:
# I onlu want to see those people whose age is above 30

In [40]:
df2[df2["Age"]>30]

    Name  Age    City  Salary
1   Anna   34   Paris    7000
3  Linda   42  London   85000

In [41]:
# I onlu want to see those people whose age is above 30 and their city must be paris

In [42]:
df2[(df2["Age"]>30) & (df2["City"]=='Paris')]

   Name  Age   City  Salary
1  Anna   34  Paris    7000

In [43]:
df2[df2["City"]=='Berlin']

    Name  Age    City  Salary
2  Peter   29  Berlin   62000